language: objective-c
osx_image: xcode8
script:
  - set -o pipefail
  - xcodebuild clean | xcpretty
  - xcodebuild test -project SwiftTweaks.xcodeproj -scheme 'SwiftTweaks' -sdk iphonesimulator -configuration Release -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' ENABLE_TESTABILITY=YES | xcpretty
